[project]
name = "pebbledoc"
version = "0.1.0"
description = "Lightweight API documentation generator for GitHub markdown."
authors = [
    { name = "Milan Staffehl", email = "milan.staffehl@gmail.com" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "docutils>=0.23",
]
keywords = [
    "documentation",
    "docs",
    "doctools",
    "autodocs",
    "rst",
    "rest",
    "restructuredtext",
    "markdown",
    "github-markdown",
]
classifiers = [
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Documentation",
    "Topic :: Software Development :: Documentation",
    "Typing :: Typed",
]

# urls
[project.urls]
Github = "https://github.com/MilanStaffehl/pebbledoc"
Homepage = "https://github.com/MilanStaffehl/pebbledoc"
Issues = "https://github.com/MilanStaffehl/pebbledoc/issues"
Changelog = "https://github.com/MilanStaffehl/pebbledoc/blob/main/CHANGELOG.md"

# build system
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyrefly>=1.1.1",
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]

# entry points
[project.scripts]
pebbledoc = "pebbledoc.cli_logic:main"


# tools
[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "W", "B", "C901", "RUF100", "RUF101", "RUF200"]

[tool.ruff.lint.pycodestyle]
max-line-length = 88

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.isort]
src_paths = ["src/pebbledoc", "tests"]
known_first_party = ["pebbledoc"]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.pyrefly]
project-includes = ["**/*.py*"]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/*venv/**",
    "**/.[!/.]*/**",
]
use-ignore-files = true
search-path = ["src", "tests/acceptance/resources", "tests"]
python-version = "3.13"

[tool.pebbledoc]
package = "pebbledoc"
